<div class = "customers form">
    <?= $this->Form->create('Customer',['url' => ['controller' => 'AdminCustomers','action' => 'edit']]); ?>
    <?= $this->Form->input('first_name',array(
        'label' => '名前',
        'class' => 'form-control')); ?>
    <?= $this->Form->input('last_name',array(
        'label' => '苗字',
        'class' => 'form-control')); ?>
    <?= $this->Form->input('first_name_kana',array(
        'label' => 'ふりがな',
        'class' => 'form-control')); ?>
    <?= $this->Form->input('last_name_kana',array(
        'label' => '',
        'class' => 'form-control')); ?>
    <?= $this->Form->input('gender',array(
        'label' => '性別',
        'type' => 'select',
        'options' => $gender,
        'class' => 'form-control')); ?>
    <?= $this->Form->input('email',array(
        'label' => 'メールアドレス',
        'class' => 'form-control')); ?>
    <?= $this->Form->input('postal_code',array(
        'label' => '郵便番号',
        'class' => 'form-control')); ?>
    <?= $this->Form->input('prefecture',array(
        'label' => '都道府県',
        'class' => 'form-control')); ?>
    <?= $this->Form->input('address1',array(
        'label' => '市区町村',
        'class' => 'form-control')); ?>
    <?= $this->Form->input('address2',array(
        'label' => '番地・建物名',
        'class' => 'form-control')); ?>
    <?= $this->Form->input('phone_number',array(
        'label' => '電話番号',
        'class' => 'form-control')); ?>
    <?= $this->Form->input('prime-flg',array(
        'label' => '会員区分',
        'type' => 'select',
        'options' => $prime_flg,
        'class' => 'form-control')); ?>
    <?= $this->Form->input('created',array(
        'label' => '作成日時')); ?>
    <?= $this->Form->input('modified',array(
        'label' => '更新日時')); ?>
    <?= $this->Form->hidden('id'); ?>
    <?= $this->Form->end(__('更新')); ?>

</div>